import Head from "next/head";
import Navbar from "../components/navbar"
import { Inter } from "@next/font/google";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const [convos, setConvos] = useState([]);

    useEffect(() => {
        
    }, []);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Health and Wellness Forum</h1>
                <h2>Recent Converstaions</h2>
                <ul>
                    {convos.map((convo: any) => (
                        <li key={convo.id}>
                            <a href={`/convos/${convo.id}`}>{convo.title}</a>
                        </li>
                    ))}
                </ul>
            </main>
        </>
    );
}
